version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    environment:
      SECRET_KEY: ${SECRET_KEY}
      HOST: 0.0.0.0
      PORT: ${PORT}

      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASS: ${POSTGRES_DB_PASS}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_DATABASE: ${POSTGRES_DB_DATABASE}

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: